""" Added cascade attribute on User and UserRoles model 

Revision ID: c0a220d32d6f
Revises: a5fbf2980444
Create Date: 2026-06-09 09:55:13.055993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0a220d32d6f'
down_revision = 'a5fbf2980444'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('user_roles_roleId_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('user_roles_userId_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['userId'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'roles', ['roleId'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('user_roles_userId_fkey'), 'users', ['userId'], ['id'])
        batch_op.create_foreign_key(batch_op.f('user_roles_roleId_fkey'), 'roles', ['roleId'], ['id'])

    # ### end Alembic commands ###
